version: 2.1

workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          context:
            - gemfury
          filters:
            # only publish gem after cutting tag
            tags:
              only: /.*/
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - service-{{ checksum "salesforce_bulk_api.gemspec" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: service-{{ checksum "salesforce_bulk_api.gemspec" }}

  publish:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - run:
          name: Build and publish gem to gemfury
          command: ./.circleci/publish.sh
